spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
    username: ${SPRING_DATASOURCE_USERNAME:stats}
    password: ${SPRING_DATASOURCE_PASSWORD:stats}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090
  address: 0.0.0.0