spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/stats
    username: stats
    password: stats
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health
