spring:
  datasource:
    url: jdbc:postgresql://ewm-main-db:5432/ewm
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate # Используйте 'update' для разработки, 'validate' для продакшена
    show-sql: true
    open-in-view: false

server:
  port: 8080
  address: 0.0.0.0

stats:
  service:
    url: http://stats-service:9090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE