spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://main-db:5432/main}
    username: ${SPRING_DATASOURCE_USERNAME:main}
    password: ${SPRING_DATASOURCE_PASSWORD:main}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  address: 0.0.0.0

stats:
  service:
    url: ${STATS_SERVICE_URL:http://stats-server:9090}

management:
  endpoints:
    web:
      exposure:
        include: health,info  # можно добавить: metrics,prometheus
  endpoint:
    health:
      show-details: always
  server:
    port: 8080

