spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ewm-db:5432/ewm_main_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

stats:
  service:
    url: ${STATS_SERVICE_URL:http://stats-server:9090}
