name: Explore With Me API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: explore_with_me
          POSTGRES_USER: explore
          POSTGRES_PASSWORD: explore
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U explore -d explore_with_me"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build ewm-stats-service jar
        working-directory: ./ewm-stats-service
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t stats-service ./ewm-stats-service

      - name: Start docker-compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services
        run: |
          chmod +x ./wait-for-it.sh
          ./wait-for-it.sh localhost:9090 -t 120

      - name: Run API tests
        run: mvn test -P api-tests
