name: CI - Stats Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stats
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start stats-server
        run: |
          docker compose -f docker-compose.yml up -d --build stats-db stats-server

      - name: Wait for Postgres to be ready
        run: |
          until docker exec $(docker ps -qf "name=stats-db") pg_isready -U postgres; do
            echo "Waiting for Postgres..."
            sleep 5
          done

      - name: Run tests
        run: |
          # Здесь запускаем тесты Java (Maven/Gradle)
          ./mvnw clean test

      - name: Shutdown containers
        run: docker compose -f docker-compose.yml down -v
