name: Explore With Me API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: explore_with_me
          POSTGRES_USER: explore
          POSTGRES_PASSWORD: explore
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U explore -d explore_with_me"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build entire project (skip tests)
        run: mvn clean install -DskipTests

      - name: Build Docker image for stats-service
        run: docker build -t stats-server ./ewm-stats-service

      - name: Start docker-compose services
        run: docker compose -f docker-compose.yml up -d --build

      - name: Check running containers
        run: docker ps -a

      - name: Wait for stats-server health endpoint
        run: |
          echo "⏳ Waiting for stats-server actuator health..."
          for i in {1..60}; do
            if curl -s http://localhost:9090/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "✅ Stats-server is healthy"
              exit 0
            fi
            echo "Waiting... ($i/60)"
            sleep 5
          done
          echo "❌ Stats-server did not become healthy. Showing logs:"
          docker logs $(docker ps -qf "name=stats-server")
          exit 1

      - name: Run API tests
        run: mvn test -P api-tests
