name: Explore With Me API Tests

on:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: explore_with_me
          POSTGRES_USER: explore
          POSTGRES_PASSWORD: explore
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U explore -d explore_with_me"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build entire project (skip tests)
        run: mvn clean install -DskipTests

      - name: Build Docker images
        run: |
          docker build -t stats-server ./ewm-stats-service
          docker build -t main-server ./ewm-main-service

      - name: Start docker-compose services
        run: docker compose -f docker-compose.yml up -d

      - name: Check running containers
        run: docker ps -a

      - name: Show logs of stats-server (debug)
        run: docker logs $(docker ps -qf "name=stats-server") || true

      - name: Wait for stats-server health endpoint
        run: |
          chmod +x .github/workflows/wait-for-it.sh
          echo "⏳ Waiting for stats-server:9090/actuator/health ..."
          .github/workflows/wait-for-it.sh stats-server:9090 -t 300
          curl -s --retry 30 --retry-delay 5 --retry-connrefused http://localhost:9090/actuator/health

      - name: Run API tests
        run: mvn test -P api-tests
