name: Explore With Me API Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Start app in background
        run: |
          java -jar target/ewm-stats-service-0.0.1-SNAPSHOT.jar &
        background: true

      - name: Wait for service to be available
        run: |
          # Ждем 90 секунд, проверяем health endpoint
          timeout 90 bash -c '
          until curl --silent --fail http://localhost:9090/actuator/health | grep -q UP; do
            echo "Waiting for service..."
            sleep 2
          done
          '

      - name: Run API tests
        run: mvn test
